function h = incidental_print(var_name,r,Tstep1_v1,Estep1_v1,Estep1_v2,fileID)

fprintf(fileID,'%s\n',strcat(var_name,'&', ...
                            num2str(Tstep1_v1(r),'%5.2f'),'&',...
                            num2str(Estep1_v1(r),'%5.2f'),'&',...
                            num2str((Estep1_v1(r)-Tstep1_v1(r))./Tstep1_v1(r),'%5.2f'),'&',...
                            num2str(Estep1_v2(r),'%5.2f'),'&',...
                            num2str((Estep1_v2(r)-Tstep1_v1(r))./Tstep1_v1(r),'%5.2f'),'\\'));
                        
                        h=1;