function  h=PRC(ptile,var,t)

h = repelem((...
                   (accumarray(repelem((1:length(t))',t,1),var)./t) ...
               <= prctile((accumarray(repelem((1:length(t))',t,1),var)./t)...
               ,ptile)...
               ),t,1);