function h = sig_guess_table...
    (est_version,tag,controls,sample,size_smp,boot_max,mac,cd_dir,cd_out)

h=1;
% generate step 1 estimates

if length(controls)>=5
    SHH_control=controls(5);
else
    SHH_control=0;
end

%t = data_prepc_v4(est_version,sample,size_smp,mac,tag,control_size,0,[]);

%OBS=sum(t);
%HH=length(t);

X_ORIGINAL = [ csvread(strcat(cd_dir,'results/x',num2str(est_version+1),'.csv')) ...
               csvread(strcat(cd_dir,'results/x',num2str(est_version),'.csv')) ...
               csvread(strcat(cd_dir,'results/x',num2str(est_version+2),'.csv')) ...
                ];
  
Xmean = X_ORIGINAL(1:sum(controls(1:3)+SHH_control),:);

HLINE=0;
as   =2; % START TWO EARLIER WITH NEW SCHEME!

fileID = fopen(strcat(cd_out,'tables/sig_guess_estimates.tex'),'w');

%fprintf(fileID,'%s\n','\begin{table}');
%fprintf(fileID,'%s\n','\centering');

%fprintf(fileID,'%s\n','\caption{Step 1: Demand Estimates}'); 
fprintf(fileID,'%s\n','\begin{tabular}{lccc}');
%fprintf(fileID,'%s\n','\toprule');
%fprintf(fileID,'%s\n','\hline');
fprintf(fileID,'%s\n','& $[\sigma_{\nu} < 3.53]$ & $[3.53 < \sigma_{\nu} < 7.06]$ &  $[7.06 < \sigma_{\nu} < 10.59]$ \\');


%%%%%%% ALPHA! (PUT MORE IN AND DESCRIBE THEM)

fprintf(fileID,'%s\n',strcat('Price Sensitivity : $\alpha$ &', ...
                    ' ','&', ...
                    ' ','&', ...                    
                    ' ','\\'));
fprintf(fileID,'%s\n','\hline');
%fprintf(fileID,'%s\n','\hline');
                
fprintf(fileID,'%s\n',strcat('Intercept &', ...
                    num2str(Xmean(11-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(11-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(11-as,3),'%5.2f'),'\\'));
                

if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('HHsize 4 to 5 &', ...
                    num2str(Xmean(12-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(12-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(12-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('HHsize over 5 &', ...
                    num2str(Xmean(13-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(13-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(13-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Apartment &', ...
                    num2str(Xmean(14-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(14-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(14-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Single House &', ...
                    num2str(Xmean(15-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(15-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(15-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Low Skill Emp. &', ...
                    num2str(Xmean(16-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(16-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(16-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Over 2 Empl. Members &', ...
                    num2str(Xmean(17-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(17-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(17-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end

%%% NOTE THAT THE ORDER IS REVERSED HERE !!!
    fprintf(fileID,'%s\n',strcat('HH Head 36 to 52 years  &', ...
                    num2str(Xmean(19-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(19-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(19-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end

fprintf(fileID,'%s\n',strcat('HH Head Over 52 &', ...
                    num2str(Xmean(18-as,1),'%5.2f'),'&', ...
                    num2str(Xmean(18-as,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(18-as,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end

%%%%% SIG EP
fprintf(fileID,'%s\n',strcat(' &', ...
                    ' ','&', ...
                    ' ','&', ...                    
                    ' ','\\'));
                
fprintf(fileID,'%s\n',strcat('Consumption Shock : $\sigma_{\nu}$ &', ...
                    ' ','&', ...
                    ' ','&', ...                    
                    ' ','\\'));
    fprintf(fileID,'%s\n','\hline');
  %  fprintf(fileID,'%s\n','\hline');                     

fprintf(fileID,'%s\n',strcat('Single HH &', ...
                    num2str(Xmean(1,1),'%5.2f'),'&', ...
                    num2str(Xmean(1,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(1,3),'%5.2f'),'\\'));
           
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Two HHs &', ...
                    num2str(Xmean(2,1),'%5.2f'),'&', ...
                    num2str(Xmean(2,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(2,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Three plus HHs &', ...
                    num2str(Xmean(3,1),'%5.2f'),'&', ...
                    num2str(Xmean(3,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(3,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end

%%%%%%% QUINTILE OF CONSUMPTION %%%%%%%%

fprintf(fileID,'%s\n',strcat(' &', ...
                    ' ','&', ...
                    ' ','&', ...                    
                    ' ','\\'));
fprintf(fileID,'%s\n',strcat('Preference Shock : $\sigma_{\psi}$ &', ...
                    ' ','&', ...
                    ' ','&', ...                    
                    ' ','\\'));
    fprintf(fileID,'%s\n','\hline');
%    fprintf(fileID,'%s\n','\hline');     

fprintf(fileID,'%s\n',strcat('Intercept &', ...
                    num2str(Xmean(4,1),'%5.2f'),'&', ...
                    num2str(Xmean(4,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(4,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Below 1st Quintile Usage &', ...
                    num2str(Xmean(5,1),'%5.2f'),'&', ...
                    num2str(Xmean(5,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(5,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Over 3rd Quintile Usage &', ...
                    num2str(Xmean(6,1),'%5.2f'),'&', ...
                    num2str(Xmean(6,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(6,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Two HHs &', ...
                    num2str(Xmean(7,1),'%5.2f'),'&', ...
                    num2str(Xmean(7,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(7,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Three HHs &', ...
                    num2str(Xmean(8,1),'%5.2f'),'&', ...
                    num2str(Xmean(8,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(8,3),'%5.2f'),'\\'));

                %{
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end

%%%%%%% SHH!
fprintf(fileID,'%s\n',strcat('Two HHs &', ...
                    num2str(Xmean(9,1),'%5.2f'),'&', ...
                    num2str(Xmean(9,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(9,3),'%5.2f'),'\\'));
if HLINE==1
    fprintf(fileID,'%s\n','\hline');
end
fprintf(fileID,'%s\n',strcat('Three plus HHs &', ...
                    num2str(Xmean(10,1),'%5.2f'),'&', ...
                    num2str(Xmean(10,2),'%5.2f'),'&', ...                    
                    num2str(Xmean(10,3),'%5.2f'),'\\'));
%}
                    
fprintf(fileID,'%s\n','\bottomrule');

fprintf(fileID,'%s\n','\end{tabular} \\'); 

%fprintf(fileID,'%s\n','\vspace{.5cm}'); 

%fprintf(fileID,'%s\n','\label{table:step1estimates}'); 
%fprintf(fileID,'%s','   Rate Change Accounts:  ');
%fprintf(fileID,'%s\n',num2str(R_to_S));
            
%fprintf(fileID,'%s\n','\end{table}')s;                

fclose(fileID);


