function h = table_print_welfare(type, r, format,percent, fileID ,RES_first, RES_current, RES_tpt0, RES_tpt1, RES_tpt3_0, RES_tpt3_1)

h = 1;

if percent==1
    fprintf(fileID,'%s\n',strcat(type,num2str(100.*RES_first(r),format),'\% &', ...
                                        num2str(100.*RES_current(r),format),'\% &', ...
                                        num2str(100.*RES_tpt0(r),format),'\% &',...
                                         num2str(100.*RES_tpt1(r),format),'\% &',...
                                         num2str(100.*RES_tpt3_0(r),format),'\% &',...
                                         num2str(100.*RES_tpt3_1(r),format),'\%',...
                                        '\\'));
                                    
else
    fprintf(fileID,'%s\n',strcat(type,num2str(RES_first(r),format),'&', ...
                                        num2str(RES_current(r),format),'&', ...
                                        num2str(RES_tpt0(r),format),'&',...
                                         num2str(RES_tpt1(r),format),'&',...
                                         num2str(RES_tpt3_0(r),format),'&',...
                                         num2str(RES_tpt3_1(r),format),...
                                        '\\'));
                                    
end