function out1 = d1_alpha0(alpha1,pr)
%D1_ALPHA0
%    OUT1 = D1_ALPHA0(ALPHA1,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:12:44

out1 = 1.0./(alpha1.*pr.*2.0+1.0);
