function out1 = d1_alpha1(alpha0,alpha1,pi,pr,theta1)
%D1_ALPHA1
%    OUT1 = D1_ALPHA1(ALPHA0,ALPHA1,PI,PR,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:12:43

out1 = -1.0./(alpha1.*pr.*2.0+1.0).^2.*(pi+alpha0.*pr.*2.0+pr.*theta1.*2.0);
