function out1 = d2_alpha1(alpha0,alpha1,pi,pr,theta1)
%D2_ALPHA1
%    OUT1 = D2_ALPHA1(ALPHA0,ALPHA1,PI,PR,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:17:33

out1 = pr.*1.0./(alpha1.*pr.*2.0+1.0).^3.*(pi+alpha0.*pr.*2.0+pr.*theta1.*2.0).*4.0;
