function out1 = d_alpha1_alpha0(alpha1,pr)
%D_ALPHA1_ALPHA0
%    OUT1 = D_ALPHA1_ALPHA0(ALPHA1,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:20:50

out1 = pr.*1.0./(alpha1.*pr.*2.0+1.0).^2.*-2.0;
