function [name1,name2] = d_alpha0(alpha1,pr)
%D_ALPHA0
%    [NAME1,NAME2] = D_ALPHA0(ALPHA1,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:20:17

name1 = 1.0./(alpha1.*pr.*2.0+1.0);
if nargout > 1
    name2 = 0.0;
end
