function [name1,name2] = d_alpha1(alpha0,alpha1,pi,pr,theta1)
%D_ALPHA1
%    [NAME1,NAME2] = D_ALPHA1(ALPHA0,ALPHA1,PI,PR,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Jun-2020 17:19:14

t2 = alpha0.*pr.*2.0;
t3 = alpha1.*pr.*2.0;
t4 = pr.*theta1.*2.0;
t5 = t3+1.0;
t6 = pi+t2+t4;
name1 = -1.0./t5.^2.*t6;
if nargout > 1
    name2 = pr.*1.0./t5.^3.*t6.*4.0;
end
