function [val,g,h] = gh1(alpha0,alpha1,nc,np,p_i,p_r,sig,theta1,wobs)
%GH1
%    [VAL,G,H] = GH1(ALPHA0,ALPHA1,NC,NP,P_I,P_R,SIG,THETA1,WOBS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Jun-2020 10:33:16

t2 = alpha1.*p_i;
t3 = alpha0.^2;
t4 = alpha1.^2;
t5 = p_i.^2;
t6 = p_r.^2;
t7 = sig.^2;
t8 = theta1.^2;
t9 = wobs.^2;
t10 = alpha0.*p_r.*2.0;
t11 = alpha1.*p_r.*2.0;
t12 = alpha0.*p_r.*4.0;
t13 = p_r.*theta1.*2.0;
t14 = p_r.*theta1.*4.0;
t15 = p_r.*wobs.*2.0;
t16 = -alpha0;
t18 = 1.0./sig.^3;
t19 = -theta1;
t17 = 1.0./t7;
t20 = -t2;
t21 = -t15;
t22 = p_r.*t2.*2.0;
t23 = t11.*wobs;
t24 = -t7;
t25 = t11+1.0;
t27 = alpha1.*p_r.*t7.*4.0;
t28 = alpha1.*t6.*wobs.*4.0;
t35 = p_i+t10+t13;
t36 = t4.*t6.*t7.*4.0;
t26 = -t22;
t29 = -t27;
t30 = -t28;
t31 = alpha0+t20+theta1;
t32 = 1.0./t25;
t37 = -t36;
t38 = t2+t16+t19+t23+wobs;
t33 = t32.^2;
t34 = t32.^3;
t39 = t31.*t32;
val = -log(exp(t17.*(t39-wobs).^2.*(-1.0./2.0))./(nc.*sig));
if nargout > 1
    g = [np.*t17.*t32.*(t39-wobs),np.*t17.*t34.*t35.*t38,-np.*t18.*t33.*(t3+t8+t9+t24+t29+t37-alpha0.*t2.*2.0+alpha0.*theta1.*2.0-alpha0.*wobs.*2.0-t2.*theta1.*2.0+t2.*wobs.*2.0-theta1.*wobs.*2.0+t2.^2+alpha1.*p_r.*t9.*4.0+t4.*t6.*t9.*4.0-alpha0.*alpha1.*p_r.*wobs.*4.0+alpha1.*p_r.*t2.*wobs.*4.0-alpha1.*p_r.*theta1.*wobs.*4.0)];
end
if nargout > 2
    t42 = p_i+t12+t14+t21+t26+t30;
    t40 = -t39;
    t43 = np.*t18.*t33.*t38.*2.0;
    t44 = np.*t18.*t34.*t35.*t38.*2.0;
    t45 = np.*t17.*t34.*t42;
    t41 = t40+wobs;
    t46 = -t44;
    t47 = -t45;
    h = [np.*t17.*t33,t47,t43,t47,np.*t17.*t33.^2.*t35.*(p_i+alpha0.*p_r.*6.0-p_r.*t2.*4.0+p_r.*theta1.*6.0-p_r.*wobs.*4.0-alpha1.*t6.*wobs.*8.0),t46,t43,t46,np.*t17.^2.*t33.*(t3.*3.0+t8.*3.0+t9.*3.0+t24+t29+t37-alpha0.*t2.*6.0+alpha0.*theta1.*6.0-alpha0.*wobs.*6.0-t2.*theta1.*6.0+t2.*wobs.*6.0-theta1.*wobs.*6.0+t2.^2.*3.0+alpha1.*p_r.*t9.*1.2e+1+t4.*t6.*t9.*1.2e+1-alpha0.*alpha1.*p_r.*wobs.*1.2e+1+alpha1.*p_r.*t2.*wobs.*1.2e+1-alpha1.*p_r.*theta1.*wobs.*1.2e+1)];
end
