function [val,g,h] = gh3(AC,A_1,A_2,alpha1,alpha0_1,alpha0_2,nc,np,p_i,p_r,sig,theta1,wobs)
%GH3
%    [VAL,G,H] = GH3(AC,A_1,A_2,ALPHA1,ALPHA0_1,ALPHA0_2,NC,NP,P_I,P_R,SIG,THETA1,WOBS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Jun-2020 14:02:06

t2 = A_1.*alpha0_1;
t3 = A_2.*alpha0_2;
t4 = alpha1.*p_i;
t5 = A_1.^2;
t6 = A_2.^2;
t7 = alpha1.^2;
t8 = p_r.^2;
t9 = sig.^2;
t10 = wobs.^2;
t11 = AC.*p_r.*2.0;
t12 = AC.*p_r.*4.0;
t13 = alpha1.*p_r.*2.0;
t14 = p_r.*theta1.*2.0;
t15 = p_r.*theta1.*4.0;
t16 = p_r.*wobs.*2.0;
t17 = 1.0./nc;
t19 = 1.0./sig.^3;
t21 = -wobs;
t32 = alpha1.*p_r.*wobs.*-2.0;
t18 = 1.0./t9;
t22 = -t4;
t23 = -t16;
t24 = p_r.*t2.*2.0;
t25 = p_r.*t2.*4.0;
t26 = p_r.*t3.*2.0;
t27 = p_r.*t3.*4.0;
t28 = p_r.*t4.*2.0;
t29 = t13.*wobs;
t30 = t13+1.0;
t33 = alpha1.*t8.*wobs.*4.0;
t20 = t18.^2;
t31 = -t28;
t34 = -t33;
t35 = 1.0./t30;
t38 = AC+t2+t3+t22+theta1;
t40 = p_i+t11+t14+t24+t26;
t36 = t35.^2;
t37 = t35.^3;
t41 = t35.*t38;
t42 = t21+t32+t38;
t48 = p_i+t12+t15+t23+t25+t27+t31+t34;
t39 = A_1.*A_2.*np.*t18.*t36;
t43 = -t41;
t45 = (t41-wobs).^2;
t50 = A_1.*np.*t19.*t36.*t42.*2.0;
t51 = A_2.*np.*t19.*t36.*t42.*2.0;
t54 = A_1.*np.*t18.*t37.*t48;
t55 = A_2.*np.*t18.*t37.*t48;
t58 = np.*t19.*t37.*t40.*t42.*2.0;
t44 = t43+wobs;
t46 = (t18.*t45)./2.0;
t52 = -t50;
t53 = -t51;
t56 = -t54;
t57 = -t55;
t47 = -t46;
t49 = exp(t47);
val = -log((t17.*t49)./sig);
if nargout > 1
    g = [A_1.*np.*t18.*t35.*(t41-wobs),A_2.*np.*t18.*t35.*(t41-wobs),-np.*t18.*t37.*t40.*t42,nc.*np.*sig.*exp(t46).*(t17.*t18.*t49-t17.*t20.*t45.*t49)];
end
if nargout > 2
    h = [np.*t5.*t18.*t36,t39,t56,t52,t39,np.*t6.*t18.*t36,t57,t53,t56,t57,np.*t18.*t36.^2.*t40.*(p_i+AC.*p_r.*6.0+p_r.*t2.*6.0+p_r.*t3.*6.0-p_r.*t4.*4.0+p_r.*theta1.*6.0-p_r.*wobs.*4.0-alpha1.*t8.*wobs.*8.0),t58,t52,t53,t58,np.*t20.*t36.*(-t9+t10.*3.0+AC.*t2.*6.0+AC.*t3.*6.0-AC.*t4.*6.0+AC.*theta1.*6.0-AC.*wobs.*6.0+t2.*t3.*6.0-t2.*t4.*6.0-t3.*t4.*6.0+t2.*theta1.*6.0+t3.*theta1.*6.0-t4.*theta1.*6.0-t2.*wobs.*6.0-t3.*wobs.*6.0+t4.*wobs.*6.0-theta1.*wobs.*6.0+AC.^2.*3.0+t2.^2.*3.0+t3.^2.*3.0+t4.^2.*3.0+theta1.^2.*3.0-alpha1.*p_r.*t9.*4.0+alpha1.*p_r.*t10.*1.2e+1-t7.*t8.*t9.*4.0+t7.*t8.*t10.*1.2e+1-alpha1.*p_r.*t2.*wobs.*1.2e+1-alpha1.*p_r.*t3.*wobs.*1.2e+1+alpha1.*p_r.*t4.*wobs.*1.2e+1-alpha1.*p_r.*theta1.*wobs.*1.2e+1-AC.*alpha1.*p_r.*wobs.*1.2e+1)];
end
