function [EV,OV,KV,UV,AV,AVB,AVN,TV,TVB,TVN] = ghu7_input(AC,A_1,A_2,TC,TCb,TCn,T_1,T_2,T_1b,T_2b,T_1n,T_2n,alpha1,alpha0_1,alpha0_2,nc,p_i,sig,siga,theta0_1,theta0_2,wobs,y,yb)
%GHU7_INPUT
%    [EV,OV,KV,UV,AV,AVB,AVN,TV,TVB,TVN] = GHU7_INPUT(AC,A_1,A_2,TC,TCB,TCN,T_1,T_2,T_1B,T_2B,T_1N,T_2N,ALPHA1,ALPHA0_1,ALPHA0_2,NC,P_I,SIG,SIGA,THETA0_1,THETA0_2,WOBS,Y,YB)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jul-2020 17:37:04

t2 = A_1.*alpha0_1;
t3 = A_2.*alpha0_2;
t4 = TCb.*p_i;
t5 = TCn.*p_i;
t6 = T_1.*theta0_1;
t7 = T_2.*theta0_2;
t8 = T_1b.*theta0_1;
t9 = T_2b.*theta0_2;
t10 = T_1n.*theta0_1;
t11 = T_2n.*theta0_2;
t12 = alpha1.*p_i;
t17 = 1.0./alpha1;
t18 = 1.0./sig.^2;
t19 = -wobs;
t13 = p_i.*t8;
t14 = p_i.*t9;
t15 = p_i.*t10;
t16 = p_i.*t11;
t20 = -t12;
t21 = TCb+t8+t9;
t22 = TCn+t10+t11;
t23 = t20+t21;
t24 = t20+t22;
t31 = AC+TC+t2+t3+t6+t7+t19+t20;
t25 = t23.^2;
t26 = t24.^2;
t29 = AC+t2+t3+t23;
t30 = AC+t2+t3+t24;
t32 = t31.^2;
t27 = t25./2.0;
t28 = t26./2.0;
t33 = t21.*t29;
t34 = t22.*t30;
t35 = -t33;
t36 = -t34;
t37 = t27+t35;
t38 = t28+t36;
t39 = t17.*t37;
t40 = t17.*t38;
EV = erf((sqrt(2.0).*(-t4+t5-t13-t14+t15+t16-t39+t40+wobs-y+yb))./(siga.*2.0))./2.0+1.0./2.0;
if nargout > 1
    OV = exp(t18.*t32.*(-1.0./2.0))./(nc.*sig);
end
if nargout > 2
    KV = t18.*t32;
end
if nargout > 3
    UV = t4-t5+t13+t14-t15-t16+t39-t40+y-yb;
end
if nargout > 4
    AV = AC+TC+t2+t3+t6+t7+t20;
end
if nargout > 5
    AVB = t29;
end
if nargout > 6
    AVN = t30;
end
if nargout > 7
    TV = TC+t6+t7;
end
if nargout > 8
    TVB = t21;
end
if nargout > 9
    TVN = t22;
end
