function [UV,AVB,AVN,TVB,TVN] = ghu9_input(AC,A_1,A_2,TCb,TCn,T_1b,T_2b,T_1n,T_2n,alpha1,alpha0_1,alpha0_2,p_i,theta0_1,theta0_2,y,yb)
%GHU9_INPUT
%    [UV,AVB,AVN,TVB,TVN] = GHU9_INPUT(AC,A_1,A_2,TCB,TCN,T_1B,T_2B,T_1N,T_2N,ALPHA1,ALPHA0_1,ALPHA0_2,P_I,THETA0_1,THETA0_2,Y,YB)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jul-2020 14:21:00

t2 = A_1.*alpha0_1;
t3 = A_2.*alpha0_2;
t4 = T_1b.*theta0_1;
t5 = T_2b.*theta0_2;
t6 = T_1n.*theta0_1;
t7 = T_2n.*theta0_2;
t8 = alpha1.*p_i;
t9 = 1.0./alpha1;
t10 = -t8;
t11 = TCb+t4+t5;
t12 = TCn+t6+t7;
t13 = AC+t2+t3+t10+t11;
t14 = AC+t2+t3+t10+t12;
UV = -y+yb-TCb.*p_i+TCn.*p_i-p_i.*t4-p_i.*t5+p_i.*t6+p_i.*t7+t9.*(t11.*t13-(t10+t11).^2./2.0)-t9.*(t12.*t14-(t10+t12).^2./2.0);
if nargout > 1
    AVB = t13;
end
if nargout > 2
    AVN = t14;
end
if nargout > 3
    TVB = t11;
end
if nargout > 4
    TVN = t12;
end
