function out1 = gus(A_1,A_2,A_3,A_4,A_5,A_6,A_7,T_1,T_2,T_3,alpha1,alpha0_1,alpha0_2,alpha0_3,alpha0_4,alpha0_5,alpha0_6,alpha0_7,g1,pi,theta1_1,theta1_2,theta1_3)
%GUS
%    OUT1 = GUS(A_1,A_2,A_3,A_4,A_5,A_6,A_7,T_1,T_2,T_3,ALPHA1,ALPHA0_1,ALPHA0_2,ALPHA0_3,ALPHA0_4,ALPHA0_5,ALPHA0_6,ALPHA0_7,G1,PI,THETA1_1,THETA1_2,THETA1_3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Jun-2020 11:46:37

out1 = [(A_1.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_2.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_3.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_4.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_5.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_6.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(A_7.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,g1,1.0./alpha1.^2.*(T_1.*theta1_1+T_3.*theta1_3).*(A_1.*alpha0_1.*2.0+A_2.*alpha0_2.*2.0+A_3.*alpha0_3.*2.0+A_4.*alpha0_4.*2.0+A_5.*alpha0_5.*2.0+A_6.*alpha0_6.*2.0+A_7.*alpha0_7.*2.0+T_1.*theta1_1+T_2.*theta1_2.*2.0+T_3.*theta1_3).*(-1.0./2.0),(T_1.*(A_1.*alpha0_1+A_2.*alpha0_2+A_3.*alpha0_3+A_4.*alpha0_4+A_5.*alpha0_5+A_6.*alpha0_6+A_7.*alpha0_7+T_1.*theta1_1+T_2.*theta1_2+T_3.*theta1_3-alpha1.*pi))./alpha1,(T_2.*(T_1.*theta1_1+T_3.*theta1_3))./alpha1,(T_3.*(A_1.*alpha0_1+A_2.*alpha0_2+A_3.*alpha0_3+A_4.*alpha0_4+A_5.*alpha0_5+A_6.*alpha0_6+A_7.*alpha0_7+T_1.*theta1_1+T_2.*theta1_2+T_3.*theta1_3-alpha1.*pi))./alpha1];
