function out1 = ua(S,alpha0,alpha1,p1,theta0,theta1,y)
%UA
%    OUT1 = UA(S,ALPHA0,ALPHA1,P1,THETA0,THETA1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-May-2020 09:34:16

out1 = y-alpha0.*p1+S.*alpha0.*theta0-(S.*alpha1.*theta0)./2.0-S.*p1.*theta1+S.^2.*theta0.*theta1+(alpha1.*p1.^2)./(S.*theta0.*2.0);
