function out1 = unl(S,alpha0,alpha1,pi,pr,theta1,y)
%UNL
%    OUT1 = UNL(S,ALPHA0,ALPHA1,PI,PR,THETA1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Jun-2020 10:34:49

t2 = alpha1.^2;
out1 = (alpha1.*y.*2.0+pi.^2.*t2+S.^2.*theta1.^2+S.*alpha0.*theta1.*2.0-alpha0.*alpha1.*pi.*2.0+pr.*t2.*y.*4.0-alpha0.^2.*alpha1.*pr.*2.0-S.*alpha1.*pi.*theta1.*2.0)./(alpha1.*(alpha1.*pr.*2.0+1.0).*2.0);
