function out1 = up(S,alpha0,alpha1,p1,theta1,y)
%UP
%    OUT1 = UP(S,ALPHA0,ALPHA1,P1,THETA1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jun-2020 17:03:50

t2 = 1.0./alpha1;
out1 = y-alpha0.*p1+(alpha1.*p1.^2)./2.0+(S.^2.*t2.*theta1.^2)./2.0-S.*p1.*theta1+S.*alpha0.*t2.*theta1;
