function out1 = up(S,alpha0,alpha1,pi,theta1,y)
%UP
%    OUT1 = UP(S,ALPHA0,ALPHA1,PI,THETA1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Jun-2020 16:22:29

t2 = 1.0./alpha1;
out1 = y-alpha0.*pi+(alpha1.*pi.^2)./2.0+(S.^2.*t2.*theta1.^2)./2.0-S.*pi.*theta1+S.*alpha0.*t2.*theta1;
