function out1 = up1(alpha0,alpha1,pi,theta1,y)
%UP1
%    OUT1 = UP1(ALPHA0,ALPHA1,PI,THETA1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 08:49:47

t2 = 1.0./alpha1;
out1 = y-alpha0.*pi-pi.*theta1+(alpha1.*pi.^2)./2.0+(t2.*theta1.^2)./2.0+alpha0.*t2.*theta1;
