function out1 = up2s(alpha0,alpha1,p_i,theta,y)
%UP2S
%    OUT1 = UP2S(ALPHA0,ALPHA1,P_I,THETA,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Jul-2020 10:59:13

out1 = (alpha0.*theta.*2.0+alpha1.*y.*2.0+theta.^2+alpha1.^2.*p_i.^2-alpha0.*alpha1.*p_i.*2.0-alpha1.*p_i.*theta.*2.0)./(alpha1.*2.0);
