function out1 = upnl(AC,A_1,A_2,TCn,T_1n,T_2n,alpha1,alpha0_1,alpha0_2,p_i,theta0_1,theta0_2,y)
%UPNL
%    OUT1 = UPNL(AC,A_1,A_2,TCN,T_1N,T_2N,ALPHA1,ALPHA0_1,ALPHA0_2,P_I,THETA0_1,THETA0_2,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jul-2020 12:22:51

t2 = T_1n.*theta0_1;
t3 = T_2n.*theta0_2;
t4 = alpha1.*p_i;
t5 = -t4;
out1 = y-AC.*p_i-TCn.*p_i-p_i.*t2-p_i.*t3+p_i.*t4+((TCn+t2+t3).*(AC+TCn+t2+t3+t5+A_1.*alpha0_1+A_2.*alpha0_2)-(TCn+t2+t3+t5).^2./2.0)./alpha1-A_1.*alpha0_1.*p_i-A_2.*alpha0_2.*p_i;
