function out1 = wbp(A_1,A_2,A_3,A_4,A_5,A_6,A_7,T_1,T_2,T_3,alpha1,alpha0_1,alpha0_2,alpha0_3,alpha0_4,alpha0_5,alpha0_6,alpha0_7,pi,sig,theta1_1,theta1_2,theta1_3,wobs)
%WBP
%    OUT1 = WBP(A_1,A_2,A_3,A_4,A_5,A_6,A_7,T_1,T_2,T_3,ALPHA1,ALPHA0_1,ALPHA0_2,ALPHA0_3,ALPHA0_4,ALPHA0_5,ALPHA0_6,ALPHA0_7,PI,SIG,THETA1_1,THETA1_2,THETA1_3,WOBS)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Jun-2020 10:54:40

out1 = (exp(1.0./sig.^2.*(-wobs+A_1.*alpha0_1+A_2.*alpha0_2+A_3.*alpha0_3+A_4.*alpha0_4+A_5.*alpha0_5+A_6.*alpha0_6+A_7.*alpha0_7+T_1.*theta1_1+T_2.*theta1_2+T_3.*theta1_3-alpha1.*pi).^2.*(-1.0./2.0)).*3.989422804014327e-1)./sig;
