function out1 = wp(S,alpha0,alpha1,pi,theta1)
%WP
%    OUT1 = WP(S,ALPHA0,ALPHA1,PI,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Jun-2020 16:22:28

out1 = alpha0+S.*theta1-alpha1.*pi;
