function out1 = wp(S,alpha0,alpha1,p1,theta1)
%WP
%    OUT1 = WP(S,ALPHA0,ALPHA1,P1,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Jun-2020 17:03:49

out1 = alpha0+S.*theta1-alpha1.*p1;
