function out1 = wp1(alpha0,alpha1,pi,theta1)
%WP1
%    OUT1 = WP1(ALPHA0,ALPHA1,PI,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Jun-2020 08:49:47

out1 = alpha0+theta1-alpha1.*pi;
