function out1 = wp2s(alpha0,alpha1,p_i,theta)
%WP2S
%    OUT1 = WP2S(ALPHA0,ALPHA1,P_I,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Jul-2020 10:59:13

out1 = alpha0+theta-alpha1.*p_i;
