function out1 = wpnl(AC,A_1,A_2,TC,T_1,T_2,alpha1,alpha0_1,alpha0_2,p_i,theta0_1,theta0_2)
%WPNL
%    OUT1 = WPNL(AC,A_1,A_2,TC,T_1,T_2,ALPHA1,ALPHA0_1,ALPHA0_2,P_I,THETA0_1,THETA0_2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Jul-2020 12:22:50

out1 = AC+TC+A_1.*alpha0_1+A_2.*alpha0_2+T_1.*theta0_1+T_2.*theta0_2-alpha1.*p_i;
