function  h = l3g2p(input,cobs,wobs,p1,p2,p3,y)

a   = input(1);
g   = input(2);
sig = input(3);
F   = input(4);


u_ind = exp( u(a,g,p1,y)./y   +   u(a,g,p2,y )./y      + u(a,g,p3,y )./y ); % IND
    w_p1_ind   = w(a,g,p1)              ;
    w_p2_ind   = w(a,g,p2)              ;
    w_p3_ind   = w(a,g,p3)              ;
    
u_12 =exp(  u(a,g,p1,y - F )./y + u(a,g,p1,y - F )./y + u(a,g,p3,y )./y ) ; % 1+2 SHR 
    w_s_12  = w(a,g,p1) + w(a,g,p1)      ;
    w_i_12  = w(a,g,p3)                  ;
u_21 = exp( u(a,g,p2,y - F )./y + u(a,g,p2,y - F )./y + u(a,g,p3,y )./y ); % 2+1 SHR 
    w_s_21  = w(a,g,p2) + w(a,g,p2)      ;
    w_i_21  = w(a,g,p3)                  ;
    
u_13 = exp( u(a,g,p1,y - F )./y + u(a,g,p1,y - F )./y + u(a,g,p2,y )./y ); % 1+3 SHR 
    w_s_13  = w(a,g,p1) + w(a,g,p1)     ;
    w_i_13  = w(a,g,p2)                 ;
u_31 =exp(  u(a,g,p3,y - F )./y + u(a,g,p3,y - F )./y + u(a,g,p2,y )./y ); % 3+1 SHR 
    w_s_31  = w(a,g,p3) + w(a,g,p3)     ;
    w_i_31  = w(a,g,p2)                 ;

u_23 =exp(  u(a,g,p2,y - F )./y + u(a,g,p2,y - F )./y + u(a,g,p1,y )./y ); % 2+3 SHR 
    w_s_23  = w(a,g,p2) + w(a,g,p2)     ;
    w_i_23  = w(a,g,p1)                 ;
u_32 =exp(  u(a,g,p3,y - F )./y + u(a,g,p3,y - F )./y + u(a,g,p1,y )./y ); % 3+2 SHR 
    w_s_32  = w(a,g,p3) + w(a,g,p3)     ;
    w_i_32  = w(a,g,p1)                 ;

u_1_3 = exp( u(a,g,p1,y - F )./y + u(a,g,p1,y - F )./y + u(a,g,p1,y - F )./y );  % 1w3 SHR 
    w_s_1_3  = w(a,g,p1) + w(a,g,p1) + w(a,g,p1)      ;
u_2_3 = exp( u(a,g,p2,y - F )./y + u(a,g,p2,y - F )./y + u(a,g,p2,y - F )./y );  % 2w3 SHR 
    w_s_2_3  = w(a,g,p2) + w(a,g,p2) + w(a,g,p2)      ;
u_3_3 = exp( u(a,g,p3,y - F )./y + u(a,g,p3,y - F )./y + u(a,g,p3,y - F )./y );  % 3w3 SHR 
    w_s_3_3  = w(a,g,p3) + w(a,g,p3) + w(a,g,p3)      ;
    
ut = u_ind + u_12 + u_21 + u_13 + u_31 + u_23 + u_32 + u_1_3 + u_2_3 + u_3_3;

pr1  = u_ind./ut;
pr2  = u_12./ut;
pr3  = u_21./ut;
pr4  = u_13./ut;
pr5  = u_31./ut;
pr6  = u_23./ut;
pr7  = u_32./ut;
pr8  = u_1_3./ut;
pr9  = u_2_3./ut;
pr10 = u_3_3./ut;

cprt = 3.*pr1 + ...
    2.*pr2 + 2.*pr3 + 2.*pr4 + 2.*pr5 + 2.*pr6 + 2.*pr7 + ...
    pr8 + pr9 + pr10;

wprob = normpdf( (wobs - w_p1_ind),0,sig ).*pr1./cprt ...
      + normpdf( (wobs - w_p2_ind),0,sig ).*pr1./cprt ...
      + normpdf( (wobs - w_p3_ind),0,sig ).*pr1./cprt ...
        + normpdf( (wobs - w_s_12),0,sig ).*pr2./cprt ...
        + normpdf( (wobs - w_i_12),0,sig ).*pr2./cprt ...
      + normpdf( (wobs - w_s_21),0,sig ).*pr3./cprt ...
      + normpdf( (wobs - w_i_21),0,sig ).*pr3./cprt ...
        + normpdf( (wobs - w_s_13),0,sig ).*pr4./cprt ...
        + normpdf( (wobs - w_i_13),0,sig ).*pr4./cprt ...
      + normpdf( (wobs - w_s_31),0,sig ).*pr5./cprt ...
      + normpdf( (wobs - w_i_31),0,sig ).*pr5./cprt ...
        + normpdf( (wobs - w_s_23),0,sig ).*pr6./cprt ...
        + normpdf( (wobs - w_i_23),0,sig ).*pr6./cprt ...
      + normpdf( (wobs - w_s_32),0,sig ).*pr7./cprt ...
      + normpdf( (wobs - w_i_32),0,sig ).*pr7./cprt ...
     + normpdf( (wobs - w_s_1_3),0,sig ).*pr8./cprt ...
     + normpdf( (wobs - w_s_2_3),0,sig ).*pr9./cprt ...
     + normpdf( (wobs - w_s_3_3),0,sig ).*pr10./cprt ;

 
h = -1.*sum( (cobs==1).*log( 3.*pr1./cprt ) + ...
             (cobs==2).*log( 2.*pr2./cprt ) + ...
             (cobs==3).*log( 2.*pr3./cprt ) + ...
             (cobs==4).*log( 2.*pr4./cprt ) + ...
             (cobs==5).*log( 2.*pr5./cprt ) + ...
             (cobs==6).*log( 2.*pr6./cprt ) + ...
             (cobs==7).*log( 2.*pr7./cprt ) + ...
             (cobs==8).*log(    pr8./cprt ) + ...
             (cobs==9).*log(    pr9./cprt ) + ...
             (cobs==10).*log(   pr10./cprt ) + log(wprob) );

 
end