function out1 = u(a,g1,p1,y)
%U
%    OUT1 = U(A,G1,P1,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 10:59:24

t2 = a./2.0;
out1 = -t2+y-g1.*(p1-1.0)+p1.^2.*t2;
