function out1 = wa(a1,g1,pi,pr)
%WA
%    OUT1 = WA(A1,G1,PI,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2020 15:16:25

out1 = (g1-a1.*pi)./(a1.*pr.*2.0+1.0);
