function out1 = ws2(a1,a2,g1,g2,pi,pr)
%WS2
%    OUT1 = WS2(A1,A2,G1,G2,PI,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2020 15:16:26

t2 = a1.*pi;
out1 = -(-g1+t2+pr.*(a1.*g2-a2.*g1.*2.0+a2.*t2))./(a1.*pr.*2.0+a2.*pr.*2.0+a1.*a2.*pr.^2.*3.0+1.0);
