function out1 = ws3(a1,a2,a3,g1,g2,g3,pi,pr)
%WS3
%    OUT1 = WS3(A1,A2,A3,G1,G2,G3,PI,PR)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Apr-2020 15:16:32

t2 = pr.^2;
out1 = -(-g1+a1.*pi+t2.*(a1.*a2.*g3+a1.*a3.*g2-a2.*a3.*g1.*3.0+a1.*a2.*a3.*pi)+pr.*(a1.*g2-a2.*g1.*2.0+a1.*g3-a3.*g1.*2.0+a1.*a2.*pi+a1.*a3.*pi))./(a1.*pr.*2.0+a2.*pr.*2.0+a3.*pr.*2.0+a1.*a2.*t2.*3.0+a1.*a3.*t2.*3.0+a2.*a3.*t2.*3.0+a1.*a2.*a3.*pr.^3.*4.0+1.0);
